version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: psych_db
    ports:
      - "7777:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent storage for Postgres data

# Define volumes for persistent storage
volumes:
  db_data:
